# -*- mode: ruby -*-
# vi:set ft=ruby sw=2 ts=2 sts=2:

# Define the number of master and worker nodes
# If this number is changed, remember to update setup-hosts.sh script with the new hosts IP details in /etc/hosts of each VM.
NUM_MASTER_NODE = 1
NUM_WORKER_NODE = 2

IP_NW = "192.168.56."
MASTER_IP_START = 10
WORKER_IP_START = 2

SYNC_FOLDER_DIR = "/home/vagrant/vagrant-ansible"

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://vagrantcloud.com/search.
  # config.vm.box = "base"
  config.vm.box = "ubuntu/bionic64"

  # Disable automatic box update checking. If you disable this, then
  # boxes will only be checked for updates when the user runs
  # `vagrant box outdated`. This is not recommended.
  config.vm.box_check_update = false

  # Create a public network, which generally matched to bridged network.
  # Bridged networks make the machine appear as another physical device on
  # your network.
  # config.vm.network "public_network"

  # Share an additional folder to the guest VM. The first argument is
  # the path on the host to the actual folder. The second argument is
  # the path on the guest to mount the folder. And the optional third
  # argument is a set of non-required options.
  # config.vm.synced_folder "../data", "/vagrant_data"

  # Provider-specific configuration so you can fine-tune various
  # backing providers for Vagrant. These expose provider-specific options.
  # Example for VirtualBox:
  #
  # config.vm.provider "virtualbox" do |vb|
  #   # Customize the amount of memory on the VM:
  #   vb.memory = "1024"
  # end
  #
  # View the documentation for the provider you are using for more
  # information on available options.

  # Provision Master Node
  config.vm.define "kubemaster01" do |node|
    MASTER_NODE_ID = 1
    # Name shown in the GUI
    node.vm.provider "virtualbox" do |vb|
        vb.name = "kubemaster01"
        vb.memory = 4096
        vb.cpus = 2
    end
    
    node.vm.hostname = "kubemaster01"
    node.vm.network :private_network, ip: IP_NW + "#{MASTER_IP_START + MASTER_NODE_ID + MASTER_IP_START}"
    node.vm.network "forwarded_port", guest: 22, host: "#{2820 + MASTER_NODE_ID}"
    node.vm.synced_folder "../", "#{SYNC_FOLDER_DIR}"
    node.vm.provision :ansible do |ansible|
        ansible.playbook = "ansible/playbook.yml"
        ansible.tags = "all"
        ansible.groups = {      
          "k8s-masters" => ["kubemaster01"]
        }
    end
  end  
  
  # Provision Worker Nodes
  (1..NUM_WORKER_NODE).each do |j|
      config.vm.define "kubeworker0#{j}" do |node|
        # Name shown in the GUI
        node.vm.provider "virtualbox" do |vb|
            vb.name = "kubeworker0#{j}"
            vb.memory = 4096
            vb.cpus = 2
        end
        node.vm.hostname = "kubeworker0#{j}"
        node.vm.network :private_network, ip: IP_NW + "#{WORKER_IP_START + j + WORKER_IP_START}"
        node.vm.network "forwarded_port", guest: 22, host: "#{2810 + j}"
        node.vm.synced_folder "../", "/home/vagrant/vagrant-ansible"
        node.vm.provision :ansible do |ansible|
            ansible.playbook = "ansible/playbook.yml"
            ansible.tags = "all"
            ansible.groups = {      
              "k8s-workers" => ["kubeworker0[1:#{j}]"]
            }
        end
      end
  end 
end 
