- name: Uninstall K8S packages
  become: yes
  apt:
    pkg:
    - kubelet
    - kubeadm
    - kubectl
    - kubernetes-cni
    state: absent

- name: Remove K8S dependencies that are no longer required
  become: yes
  apt:
    autoremove: yes

- name: Add an Apt signing key, uses whichever key is at the URL
  become: yes
  ansible.builtin.apt_key:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
    state: present

- name: Add K8S repository into sources list
  become: yes
  ansible.builtin.apt_repository:
    repo: deb http://apt.kubernetes.io/ kubernetes-xenial main
    state: present
    update_cache: yes
    filename: kubernetes

- name: Install K8S packages
  become: yes
  apt:
    pkg:
      - kubelet={{ K8S_VERSION }}-00 
      - kubeadm={{ K8S_VERSION }}-00
      - kubectl={{ K8S_VERSION }}-00
    state: present

- name: Restart kubelet service
  become: yes
  ansible.builtin.service:
    name: kubelet
    daemon_reload: yes
    state: started
    enabled: yes